#!/bin/sh

/bin/mkdir -p /Library/Managed\ Installs/Logs
/usr/bin/touch /Library/Managed\ Installs/Logs/Install.log
/usr/bin/touch /Library/Managed\ Installs/Logs/ManagedSoftwareUpdate.log
/bin/launchctl load /Library/LaunchAgents/io.fti.SplashBuddy.launch.plist

/usr/local/munki/managedsoftwareupdate --munkipkgsonly
/usr/local/munki/managedsoftwareupdate --installonly &
